version: '3.8'

services:
    app:
        build: .
        ports:
            - '8000:8000'
        command: uvicorn main:app --reload --host 0.0.0.0
        environment:
            - PROJECT_NAME=Cloud_Storage_broker
            - BACKEND_CORS_ORIGINS=["http://localhost:8000", "https://localhost:8000", "http://localhost", "https://localhost"]
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=appdb
            - POSTGRES_SERVER=db
            - PASSKEY=init_data_passkey
        volumes:
            - ./app:/app
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=appdb
        ports:
            - '5432:5432'
